apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
    creationTimestamp: "2020-10-29T17:41:09Z"
    generation: 6
    labels:
      app: hello-world-rest-api
    name: hello-world-rest-api
    namespace: default
    resourceVersion: "231134"
    selfLink: /apis/apps/v1/namespaces/default/deployments/hello-world-rest-api
    uid: b8f6ed07-8a06-4753-8d63-4c31fc3e3a7b
  spec:
    progressDeadlineSeconds: 600
    replicas: 5
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-world-rest-api
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello-world-rest-api
      spec:
        containers:
        - image: nitesh2611/hello-world-rest-api:0.0.2-RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2020-10-29T17:41:09Z"
      lastUpdateTime: "2020-10-30T07:04:48Z"
      message: ReplicaSet "hello-world-rest-api-6486959448" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-10-30T07:15:35Z"
      lastUpdateTime: "2020-10-30T07:15:35Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 6
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
